export const catalogDepartameto = [
  { id: 1, titulo: "Alta Verapaz" },
  { id: 2, titulo: "Baja Verapaz" },
  { id: 3, titulo: "Chimaltenago" },
  { id: 4, titulo: "Chiquimula" },
  { id: 5, titulo: "Guatemala" },
  { id: 6, titulo: "El Progreso" },
  { id: 7, titulo: "Escuintla" },
  { id: 8, titulo: "Huehuetenango" },
  { id: 9, titulo: "Izabal" },
  { id: 10, titulo: "Jalapa" },
  { id: 11, titulo: "Jutiapa" },
  { id: 12, titulo: "Petén" },
  { id: 13, titulo: "Quetzaltenango" },
  { id: 14, titulo: "Quiché" },
  { id: 15, titulo: "Retalhuleu" },
  { id: 16, titulo: "Sacatepequez" },
  { id: 17, titulo: "San Marcos" },
  { id: 18, titulo: "Santa Rosa" },
  { id: 19, titulo: "Sololá" },
  { id: 20, titulo: "Suchitepequez" },
  { id: 21, titulo: "Totonicapán" },
  { id: 22, titulo: "Zacapa" },
];

export const catalogRegion = [
  { id: 1, titulo: "Norte" },
  { id: 2, titulo: "Centro" },
  { id: 3, titulo: "Sur" },
  { id: 4, titulo: "Oriente" },
  { id: 4, titulo: "Occidente" },
];

export const catalogMunicipio = [
  { id: 1, titulo: "Chimaltenango" },
  { id: 2, titulo: "San José Poaquil." },
  { id: 3, titulo: "San Martín Jilotepeque." },
  { id: 4, titulo: "San Juan Comalapa." },
  { id: 5, titulo: "Santa Apolonia." },
  { id: 6, titulo: "Tecpán." },
  { id: 7, titulo: "Patzún." },
  { id: 8, titulo: "San Miguel Pochuta." },
  { id: 9, titulo: "Patzicía." },
  { id: 10, titulo: "Santa Cruz Balanyá." },
  { id: 11, titulo: "Acatenango." },
  { id: 12, titulo: "San Pedro Yepocapa." },
  { id: 13, titulo: "San Andrés Itzapa." },
  { id: 14, titulo: "Parramos." },
  { id: 15, titulo: "Zaragoza." },
  { id: 16, titulo: "El Tejar." },
];
